#ifndef VERSION_H_
#define VERSION_H_

#define WIFI_RADIO_VERSION_MAJOR 0
#define WIFI_RADIO_VERSION_MINOR 1
#define WIFI_RADIO_VERSION_PATCH 0
#define WIFI_RADIO_VERSION_STR_2(x) #x
#define WIFI_RADIO_VERSION_STR(x) WIFI_RADIO_VERSION_STR_2(x)
#define WIFI_RADIO_VERSION WIFI_RADIO_VERSION_STR(WIFI_RADIO_VERSION_MAJOR) "." WIFI_RADIO_VERSION_STR(WIFI_RADIO_VERSION_MINOR) "." WIFI_RADIO_VERSION_STR(WIFI_RADIO_VERSION_PATCH)

#endif  // VERSION_H_
